### ISSUE TITLE
geany opens with a blank space for the decoration

### ISSUE THREAD

**Issue by fossfreedom** [ilgarmehmetali/budgie-pixel-saver-applet#13]
![ubuntu budgie - new development snapshot 1 running - oracle vm virtualbox_741](https://cloud.githubusercontent.com/assets/996240/24581169/20238f9c-170e-11e7-83f0-8ff9a50672d8.png)

from terminix - if I run `geany` it opens maximized but with a blank space for the decoration.
if I unmaximized and maximize the decoration correctly disappears into the panel.

**Comment by ilgarmehmetali** [comment]
I believe https://github.com/ilgarmehmetali/budgie-pixel-saver-applet/commit/90677124f75e32fd2d340ff8a14bce17ab9862c9 should fix this issue.

**Comment by fossfreedom** [comment]
Hi - the issue is still there :(

I thinks this maybe an issue specially for GTK+2 based apps - all other apps seem to work - have tested QT based, non GTK+3 based e.g. libreoffice and GTK+3 based.  

Hexchat also suffers the same issue - again its a GTK+2 app.

**Comment by ilgarmehmetali** [comment]
Can you try to reproduce this with https://github.com/ilgarmehmetali/budgie-pixel-saver-applet/commit/d4bc04db10a013e1f4b798232e60f84217e52d7c

**Comment by ilgarmehmetali** [comment]
Also can you feel any sluggishness-slowness  with window openings.

**Comment by fossfreedom** [comment]
perfect - both hexchat and geany works without the empty space. Cheers!!!

no sluggishness on my end  - although admittedly this is a high-end laptop so it is difficult to gauge such things.
